// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL2 = import.meta.env.VITE_TRANSLATE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY2 = import.meta.env.VITE_SUPABASE_TRANSLATE_PUBLISHABLE_KEY;


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const supabase2 = createClient<Database>(SUPABASE_URL2, SUPABASE_PUBLISHABLE_KEY2, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
